!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  auto_exposure_priority: false
  backlight_compensation: false
  brightness: -20
  contrast: 60
  enable_auto_exposure: false
  enable_auto_white_balance: false
  exposure: 166
  frames_queue_size: 16
  gain: 100
  gamma: 300
  global_time_enabled: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      auto_exposure_priority: false
      backlight_compensation: false
      brightness: -20
      contrast: 60
      enable_auto_exposure: false
      enable_auto_white_balance: false
      exposure: 166
      frames_queue_size: 16
      gain: 100
      gamma: 300
      global_time_enabled: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hue: 0
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      power_line_frequency: 3
      saturation: 64
      sharpness: 50
      state: true
      type: ''
      white_balance: 4600.0
    state: []
  hue: 0
  power_line_frequency: 3
  saturation: 64
  sharpness: 50
  white_balance: 4600.0
state: []
